# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - ufs_public_release

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: ufs_public_release
